contact_links:
    - name: âš›ï¸ Feature Request or Proposal
      about: To submit a feature request or a proposal, follow the RFC process and send a pull request. Do NOT create issues for proposals.
    - name: ğŸ“ƒ Documentation Issue
      about: This issue tracker is not for documentation issues. Please file documentation issues here.
