
###########################
###########################
## Deploy GitHub Actions ##
###########################
###########################
name: NodeJS AWS SAM Deploy

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on: ['push']

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: NodeJS AWS SAM Deploy
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@master

      #############################
      # Run NodeJS AWS SAM Deploy #
      #############################
      - name: NodeJS AWS SAM Deploy
        uses: docker://admiralawkbar/aws-nodejs:latest
        env:
           AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
           AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
